- examples/QuickStart/QuickStart.ino
Will be used in all Quick Starts in docs
> Add QuickStart example

- README.md
- keywords.txt
- src/TheThingsNetwork.cpp
- src/TheThingsNetwork.h
> Remove sendString

- examples/Downlink/Downlink.ino
- src/TheThingsNetwork.cpp
- src/TheThingsNetwork.h
> add poll() as alias for sendBytes with single byte

- README.md
- library.properties
> Update README for renamed repo

- src/TheThingsNetwork.cpp
added return values to sendBytes#11
> sendBytes: Return success and error codes

- examples/ABP/ABP.ino
- examples/QuickStart/QuickStart.ino
- examples/Receive/Receive.ino
- examples/Send/Send.ino
- examples/Workshop/Workshop.ino
- src/TheThingsNetwork.cpp
Fixes errors in #54 🤔 after testing everything except workshop and sensor samples.
> Fix typo, Fix missing poll, Fix newline

- keywords.txt
- src/TheThingsNetwork.cpp
- src/TheThingsNetwork.h
with ``` TTN_``` at the begining #52
> changed the name of every #define 

- src/TheThingsNetwork.cpp
deleted it in showStatus() #53
> show the devAddr after join

- examples/PassThrough/PassThrough.ino
- src/TheThingsNetwork.cpp
- src/TheThingsNetwork.h
> Sendbytes max retries

- keywords.txt
- src/TheThingsNetwork.cpp
- src/TheThingsNetwork.h
> move TTN_HEX_* to cpp

- src/TheThingsNetwork.cpp
> fixed bug for airtime

- .editorconfig
- .travis.yaml
- .travis.yml
Once this is merged Travis should be enabled for this repo. It will ensure the library compiles.
> Add Travis YML

- .travis.yml
- src/TheThingsNetwork.cpp
To disable Travis while we fix #119
> Undo parenthesis fix and disable travis

- examples/QuickStart/Converter.js
- examples/QuickStart/Decoder.js
- examples/QuickStart/Encoder.js
- examples/QuickStart/Validator.js
For https://github.com/TheThingsNetwork/docs/issues/66
> Update PF for port

- docs/TheThingsNetwork.md
- keywords.txt
- src/TheThingsNetwork.cpp
- src/TheThingsNetwork.h
little optimizations in TheThingsNetwork.cpp
> Optimization

- examples/ABP/ABP.ino
- examples/DeviceInfo/DeviceInfo.ino
- examples/Message/Receive/Receive.ino
- examples/Message/Send/Send.ino
- examples/QuickStart/QuickStart.ino
- examples/Receive/Receive.ino
- examples/Send/Send.ino
- examples/Sensors/DHT/DHT.ino
- examples/Sensors/LightSensor/LightSensor.ino
- examples/Workshop/Workshop.ino
> Made `fp` argument in examples

- examples/Message/Receive/Receive.ino
- src/TheThingsMessage.cpp
- src/TheThingsNetwork.cpp
fixed sendPayloads (port: int to char), found error when passing *size of the buffer in the encodeSensorData() fixed it for the moment trying to find a solution with this.
> Fix sendPayload() and encodeSensorData()

- src/TheThingsNetwork.cpp
> replace Serial1 by modemStream

- .travis.yml
- src/TheThingsNetwork.cpp
- src/TheThingsNetwork.h
will change subString function in other PR  #145
> fixed compiling issues

- .travis.yml
@Nicolasdejean can you approve and merge?
> Fix test always exits with 0

- src/TheThingsNetwork.cpp
> Add error messages for join and personalize

- .travis.yml
- examples/ABP/ABP.ino
- examples/DeviceInfo/DeviceInfo.ino
- examples/Message/Receive/Receive.ino
- examples/Message/Send/Send.ino
- examples/QuickStart/QuickStart.ino
- examples/Receive/Receive.ino
- examples/Send/Send.ino
- examples/Sensors/DHT/DHT.ino
- examples/Sensors/LightSensor/LightSensor.ino
- examples/Workshop/Workshop.ino
> Made freqPlan a define

- docs/TheThingsNetwork.md
- keywords.txt
- src/TheThingsNetwork.cpp
- src/TheThingsNetwork.h
Created a calculateAirtime to inform the user and let him work with the airtime #160
> Created calculateAirtime and made airtime public

- docs/TheThingsNetwork.md
- keywords.txt
- src/TheThingsNetwork.cpp
- src/TheThingsNetwork.h
[DO NOT MERGE] I didn't understand what you wanted to do with an enum ? #133
> Added defines for the return values of sendBytes.

- src/TheThingsMessage.h
> Defaulted TTN_PIN_ LED to LED_BUILTIN

- README.md
- keywords.txt
- library.properties
@johanstokking, although the current version works fine for both staging and production, here's a 2.0 version with some of the last merged PRs as well.
Approve and merge and Arduino IDE will pick it up within an hour or so.
> Update README, bump version, fix keywords

- src/TheThingsNetwork.cpp
- src/TheThingsNetwork.h
Sleep command with then sleeping time in milliseconds as a parameter. The module awakes after the specified time with an "ok" that it's not captured because you would probably want to do other things after setting the module to sleep...
> Add sleep command

- docs/TheThingsNetwork.md
Documents sleep introduced by #170
> Document sleep

- examples/Node/Decoder.js
- examples/Node/Node.ino
By calling `node->showStatus()` and `ttn.showStatus()` it verifies that the sensors work and turns on the (green) LED.
> Update examples for landing page

- examples/Node/Decoder.js
- examples/Node/Node.ino
@johanstokking please merge (see slack)
> Revert Node from landing config

- library.properties
@johanstokking merge to publish new version:
- Added Node class (unoptimized)
- Added sleep method
- Update Node example
[full list of changes](https://github.com/TheThingsNetwork/arduino-device-lib/compare/v2.0.0...master)
> Bump version

- src/TheThingsNetwork.cpp
- src/TheThingsNetwork.h
Affects #191 
Needs testing on a RN2903 device with AS923 firmware
> AS920-923 channel plan

- src/TheThingsNetwork.cpp
- src/TheThingsNetwork.h
> Fix reset of ADR

- docs/TheThingsNetwork.md
- src/TheThingsNetwork.cpp
- src/TheThingsNetwork.h
> Pass SF to sendBytes()

- docs/CayenneLPP.md
We recently made a few changes to our docs page, so this change is reflecting that.
> update CayenneLPP docs link

- src/TheThingsNetwork.cpp
> Fix sleep time overflow

- AUTHORS
- src/TheThingsNetwork.cpp
- src/TheThingsNetwork.h
This function just call autoBaud() to wake up the module from sleep (As mentioned in the RN2483 datasheet 2.3.1).
> Wake up from sleep

- keywords.txt
- src/TheThingsNetwork.cpp
- src/TheThingsNetwork.h
Added method to return VDD read by the RN2483 or RN2903 LoRa module
> added getVDD()

- src/TheThingsNetwork.cpp
> Fix AU915 uplink DR

- src/TheThingsNetwork.h
https://github.com/TheThingsNetwork/arduino-device-lib/issues/241
> Fix for compiling on ESP32
