TheThingsNetwork/arduino-device-lib

src/TheThingsNetwork.cpp
Fix:
```
EUI: 0004A30B001B7AD2
Battery: 3213AppEUI: 70B3D57EF0000028
DevEUI: 0004A30B001B7AD2
DevAddr: 260125CD
Data Rate: 5
RX Delay 1: 1000
RX Delay 2: 2000
```
=> debugPrint > debugPrintLn

README.md, keywords.txt, src/TheThingsNetwork.cpp, src/TheThingsNetwork.h
This fixes #23 in a more clean way than #34 by letting the user set a callback to receive downlink messages.
*Note:* For now, this doesn't touch the return value, which could now become success/error codes as requested in #11, for which #37 is pending.
In `setup()` set the callback:
```c
void setup() {
// ..
ttn.onMessage(message);
// ..
}
```
Elsewhere in your sketch define `message` or whatever you call it:
```c
void message(const byte* buffer, int length, int port)
{
debugPrint("Receive " + String(length) + " bytes on port " + String(port) + ": ");
for (int i = 0; i < length; i++)
debugPrint(String(buffer[i]) + " ");
debugPrintLn();
}
```
=> Add onMessage to set callback for downlink messages

src/TheThingsNetwork.h
@johanstokking moved reset() in private and added the TTN_ to the default arguments
=> fixing the header concerning reset()

src/TheThingsNetwork.cpp, src/TheThingsNetwork.h
This fixes #90, but... I now get an empty response when I send:
```
-- LOOP
Sending: mac tx uncnf 1 with 1 bytes
Time-out
```
Any idea @johanstokking?
=> Remove time out, fixes #90

API.md, examples/QuickStart/QuickStart.ino, examples/Receive/Receive.ino, examples/Workshop/Workshop.ino, src/TheThingsNetwork.cpp, src/TheThingsNetwork.h
Changed types in example and files .cpp and .h: int to int8_t, int16_t, int32_t or size_t #103
=> Optimize types with a specific bit-size

src/TheThingsNetwork.cpp
"mac set ch status XX on" needs to be done last. Especially after "mac set ch dcycle", otherwise the channel stays off. This commit changes the order of the configuration code to fix this.
=> Configure 868 order change

docs/TheThingsNetwork.md
The references in the documentation are obsolete: it seems [the code to calculate air time](https://github.com/TheThingsNetwork/arduino-device-lib/commit/6256981705e55236f1e99378893e9471615260d1) was [removed in February 2017](https://github.com/TheThingsNetwork/arduino-device-lib/commit/ec549b37e4cbf8d4dc6f0a4a2db8b39e2eb2c3aa); TheThingsNetwork/arduino-device-lib#183.
=> Remove obsolete documentation about calculated air time

docs/TheThingsNetwork.md
Added a description of the Stream parameters passed to TheThingsNetwork library. Elaborate about Software Serial and serial on other devices.
=> Serial and SoftwareSerial port comments

docs/TheThingsNetwork.md
Reverts TheThingsNetwork/arduino-device-lib#203
because this belongs better in the Docs, where it was just added.
=> Revert "Serial and SoftwareSerial port comments"

src/TheThingsNetwork.cpp
Wait for `ok` after calling `mac save`. Waiting for an `ok` may go into an infinite loop.
=> Add a waitForOk() after mac save.

src/TheThingsNetwork.cpp
When the MCU baud rate is different from default it is necessary to "autobaud" again after the module reset. Also, the response message after a reset is not readble if the MCU is working on a different baud rate. For this reason it it neccessary to issue another "autobaud" and a SYS_GET_VER to leave unchanged the behaviour of this function, that is reply with module informations.
=> Always sync baud on reset and after module reset

docs/TheThingsNetwork.md, src/TheThingsNetwork.cpp, src/TheThingsNetwork.h
Currently there is no method to check if a node is really still joined to TTN or if the gateway/s in range, is/are still up and running.
The "join bit" of "mac get status" response is not reliable... indeed if the only gateway in range is stopped this bit continues to return 1 (joined). Nothing strange since the rule is fire-and-forget.
A work around could then use "mac set linkchk nnn". 
_This function sets the time interval for the link check process to be triggered periodically. A <value> of ‘0’ will disable the link check process. When the time interval expires, the next application packet that will be sent to the server will include a link check MAC command. Refer to the LoRaWAN Specification V1.0 document for more information on the link check configuration._
Thanks to this command …
=> Link check command feature

docs/TheThingsNetwork.md
=> Added getVDD()

src/TheThingsNetwork.cpp, src/TheThingsNetwork.h
I increased the break time condition setting up serial port to lower baud rate when writing 0 (break) on wake method
Bug could be reproduced by non stop shaking the node, with this code, seem fixed
May be we could also arrange autoBaud to reflect this change and do only one method.
=> Fixed LoRa module not waked from sleep by autoBaud sometimes

CONTRIBUTING.md, docs/TheThingsNetwork.md
I noticed 2 broken links in the TheThingsNetwork documentation. The links to the `Send.ino` and `ABP.ino` examples are broken. It looks like the filenames changed. I fixed those.
Also changed the absolute URLs to relative ones since the absolute links would point to the TheThingsNetwork repository even if you are on a forked or offline repository.
Tiny changes.
=> Fix TheThingsMessage documentation links

src/TheThingsNetwork.h
The fix for #243 introduces a regression for Arduino SAMD boards (MKR series).
This PR checks for both AVR and SAMD architecture.
=> Fix regression for Arduino SAMD boards

docs/TheThingsNetwork.md
Improved the documentation to mitigate confusion that showed in https://www.thethingsnetwork.org/forum/t/ttn-node-link-check-does-not-work/19981/18
- Calling `linkCheck` before joining has no effect.
- The `linkCheck` command is delegated to the RN2483 module by using `mac set linkchk`, which [is documented as](http://ww1.microchip.com/downloads/en/DeviceDoc/40001784C.pdf#page=29):
> When the time interval expires, the next application packet that will be sent to the server will include also a link check MAC command.
=> Enhanced documentation for linkCheck()

src/TheThingsNetwork.cpp
As is, `needsHardReset` is never set by `readLine`.
If reads are failing, when `attempt` is finally zero and causes the `while` loop to exit, it is also post-decremented and becomes 255 (since it is unsigned). Hence the condition to set `needsHardReset` is never met.
In fact, the condition `attempts<=0` is true only when the last read attempt actually succeeded. In this case, `attempt` was 1 and is decremented to 0 before the final call to `readBytesUntil` returns read>0. The `while` loop exits because `!read` is false and the value of `attempt` remains at 0, unchanged, because of short-circuited `&&`.
Use https://godbolt.org/z/000v_I as a playground to prove this to yourself.
The solution is to ignore `attempts` after the loop. It did its job already. The important question is whether …
=> Fix `readLine`'s `needsHardReset` condition

src/TheThingsMessage.h, src/appData.pb.h, src/deviceData.pb.h
`pb.h` should be an include from the local directory, therefore `#include "ph.h"` and not `#include <pb.h>`.
Compile will fail if this library is not being included from the Arduino global path, but rather from the local directory. For example if the directory structure looks like this:
```
example/
- example.ino
- src/
-- arduino-device-lib/
```
and inside example.ino we include the library as follows:
```
#include "src/arduino-device-lib/src/TheThingsNetwork.h"
```
After this change the compile is successful.
Note:
If the library is present in both the Arduino libraries directory as well as the local directory, compilation might fail due to duplicate definitions. Keep this in mind during testing.
=> pb.h should be included from the local directory

docs/TheThingsNetwork.md, examples/CheckModule/CheckModule.ino, src/TheThingsNetwork.cpp, src/TheThingsNetwork.h
This PR is related to #280 . I believe the handling of the `needsHardReset` flag could be improved, by not setting it to `false` with each call to `reset()`.
Additionally, I added a function called `checkValidModuleConnected()` to address https://github.com/TheThingsNetwork/arduino-device-lib/issues/216#issuecomment-310430834 . In this manner, the user application can call `checkValidModuleConnected()` in the `setup()` function of the Arduino code, and make sure a valid module is connected before any join attempt. This is especially important, because we need a function that returns as fast as possible when a module is not connected or incorrectly wired. For example, a call to `reset()` takes several minutes to return if a module is not connected, because of the many instructions carried …
=> Improve handling of needsHardReset flag and add method to check valid module connected to serial port
